### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by erayko-dev** [loaf-scripts/loaf_spikestrips#1]
hello, I installed the script, no issues. However when I use only **one** spike strip I get another **three** in my inventory, please help:

![image](https://user-images.githubusercontent.com/76734458/162285229-1a3388e8-55f9-45a6-807e-73685e4d02bd.png)
![image](https://user-images.githubusercontent.com/76734458/162285249-438f6ffc-d9ab-49be-a99a-fc7e1edc001c.png)
![image](https://user-images.githubusercontent.com/76734458/162285286-e153edc4-624f-45a1-965e-98e0d17cf46a.png)
![image](https://user-images.githubusercontent.com/76734458/162285436-85ab8e03-e2a3-420f-8301-e19ebd67dfaf.png)
![image](https://user-images.githubusercontent.com/76734458/162285466-ad3dcd1e-8451-443a-9a7d-9ee067a7d881.png)

**Comment by loaf-scripts** [comment]
Fixed (hopefully)
